<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://DefaultNamespace" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://DefaultNamespace" xmlns:intf="http://DefaultNamespace" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://DefaultNamespace" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="Chat">
    <complexType>
     <sequence>
      <element name="str" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="ChatResponse">
    <complexType>
     <sequence>
      <element name="ChatReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="ChatResponse">

      <wsdl:part element="impl:ChatResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="ChatRequest">

      <wsdl:part element="impl:Chat" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="ChatWebService">

      <wsdl:operation name="Chat">

         <wsdl:input message="impl:ChatRequest" name="ChatRequest">

       </wsdl:input>

         <wsdl:output message="impl:ChatResponse" name="ChatResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ChatWebServiceSoapBinding" type="impl:ChatWebService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="Chat">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="ChatRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="ChatResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="ChatWebServiceService">

      <wsdl:port binding="impl:ChatWebServiceSoapBinding" name="ChatWebService">

         <wsdlsoap:address location="http://localhost:8080/ChatWebservice/services/ChatWebService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
